### ISSUE TITLE
more discovery woes

### ISSUE THREAD

**Issue by mer2github** [donavanbecker/homebridge-platform-wemo#101]
homebridge-platform-wemo won't discover my wemo mini smart plug. i can see the support accessories include: switches, bulbs, maker, motion and netcam. does this mean the plug is not supported? was hoping it was covered under the "switches" umbrella. i look for additional platforms on github but don't anything specific to the wemo smart plug.

my config.json is just the basic config:
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:40",
        "port": 51826,
        "pin": "728-15-728"
    },
    "platforms": [
        {
            "platform": "BelkinWeMo",
            "name": "WeMo Platform",
            "expected_accessories": "1",
            "timeout": "25",
            "noMotionTimer": 60,
            "homekit_safe": "1"
        }
    ]
}

i can start homebridge (and pair it to homekit on my iPhone 5se) w/o errors, but there are no announcements of discovered accessories:

$ homebridge
[6/10/2017, 1:11:17 PM] Loaded plugin: homebridge-platform-wemo
[6/10/2017, 1:11:17 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[6/10/2017, 1:11:17 PM] ---
[6/10/2017, 1:11:17 PM] Loaded config.json with 0 accessories and 1 platforms.
[6/10/2017, 1:11:17 PM] ---
[6/10/2017, 1:11:17 PM] Loading 1 platforms...
[6/10/2017, 1:11:17 PM] [WeMo Platform] Initializing BelkinWeMo platform...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 728-15-728 │     
    └────────────┘     
                       
[6/10/2017, 1:11:17 PM] Homebridge is running on port 51826.

in homekit upon pairing homebridge it says it may need "additional confirugation" as there are no accessories associated with it. accessories folder has nothing in it and i've read the other discovery related threads and tried things like killing homebridge removing the persist and accessory dirs and restarting...

in case it matters i'm running v8.1.0 of node and installed everything this morning.

**Comment by devbobo** [comment]
The WeMo Mini Smart plug is a new device, which probably isn't supported yet. This device is no on sale in Australia so there is no way for me to implement it.

However, Belkin have announced that a Wemo HomeKit Bridge will be available in Fall, ongoing development of this plugin probably won't be required.

**Comment by airmandan** [comment]
All my mini plugs work fine.  There has to be a config issue here.

As far as the official HomeKit Bridge, I would not be at all surprised if Belkin is branding an rPi with homebridge and your plugin pre-installed.

**Comment by rasgeek** [comment]
How do you delete or replace WeMo Switch

**Comment by devbobo** [comment]
@rasgeek follow these instructions but obviously select `BelkinWeMo`
https://github.com/devbobo/homebridge-lifx-lan/wiki/Removing-a-bulb-from-Homebridge

**Comment by rasgeek** [comment]
@devbobo
I followed the instructions to a T, but Hesperus only gives me hide,rename and identify. No remove option

**Comment by devbobo** [comment]
@rasgeek in step `5`, you need to swipe left on the `Homebridge` bridge rather than the `WeMo` accessory you want to remove.

**Comment by rasgeek** [comment]
@devbobo It worked, my bad Thanks a mil.

**Comment by rasgeek** [comment]
@devbobo Setting DHCP Reservation for demo switch and devices helps with reliability ?

**Comment by Scottbee** [comment]
I seem to also be unable to add my V1 Wemo Smart Plugs. What changes need to be made to the configuration file to allow them to pair?
