### ISSUE TITLE
Garage door opener closed state

### ISSUE THREAD

**Issue by dvd2000k** [donavanbecker/homebridge-platform-wemo#117]
Hi, is there a way to generate a closed state after xx second the gate was open? I have configured the maker without sensor because i have a condominium gate that i control with a push button. After i tell siri to open the gate it remain open. Is there a way to apply a countdown to return in closed state?

Thankyou.

**Comment by rasgeek** [comment]
HI,

There is home bridge delay switch plugin you can use and set your rules based on that. so if the door opener switched is pressed you turn on delay switch[5sec] and when dely switch a goes off it turns door opener off.

https://www.npmjs.com/package/homebridge-delay-switch

**Comment by dvd2000k** [comment]
It can work... but it send another open/close command. The gate is autoclosing after xx seconds, i need a function that after xx seconds return the doorstate to close without sending another command to momentary switch.

**Comment by rasgeek** [comment]
In that case you can use a delay switch to turn the real gate switch off after xx second.

You set home kit automation rule to turn dummy switch A (auto off after 2 sec) when real switch is activated. Now set an automaton rule to turn real switch off when dummy switch turns off.

**Comment by dvd2000k** [comment]
But when the rule triggers the real switch for the close command, the gate stop in its position. Every button press generate an open/stop/close.

**Comment by vsidlu** [comment]
My workaround - WEMO MAKER - 
switch type - Momentary; 
sensor - Yes (even if I do not have one I just made wire shortcut "S" with "-" ). 
When I push to open gate - maker momentary triggers gate remote control. Home kit shows "opening". Default opening time for this plugin is 20s. After that it checks sensor and shows status "closed".
