### ISSUE TITLE
iOS Home showing Homebridge, not accessories

### ISSUE THREAD

**Issue by Mattserati** [donavanbecker/homebridge-platform-wemo#124]
I've been trying to troubleshoot this for days, and now it's time to seek help:

I have the following WEMO accessories:

![fullsizeoutput_d00e](https://user-images.githubusercontent.com/35052287/34507610-bcd6d8ec-f072-11e7-9b17-4c85d3da1c5e.jpeg)
![fullsizeoutput_d00f](https://user-images.githubusercontent.com/35052287/34507611-bd0de468-f072-11e7-80fb-d75a5de5612d.jpeg)

I have the following config.json:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:23:3E:E3:CC:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "BelkinWeMo",
		"name": "WeMo Platform",
		"doorOpenTimer": 15,
		"discovery": true

	}]
}

=======================

My log file looks like this:

<img width="1081" alt="screen shot 2018-01-03 at 10 46 19" src="https://user-images.githubusercontent.com/35052287/34507676-6bd5d870-f073-11e7-9004-d70c31d4b2a7.png">
<img width="1062" alt="screen shot 2018-01-03 at 10 46 35" src="https://user-images.githubusercontent.com/35052287/34507677-6c0a398a-f073-11e7-9953-c83c5e0781f0.png">

=======================

Yet when I add Homebridge within the Home app, I get just Homebridge under Default Room, and none of the Wemo accessories. I have had this working previously, so not sure what has changed - help appreciated.

**Comment by DMBlakeley** [comment]
I have had this happen in the past where Homebridge does not find the Wemo accessories.  My suggestion is to stop Homebridge, and delete the cachedAccessories file from the .homebridge/accessories directory.  If you are only using Wemo with Homebridge then I would also delete the files in the .homebridge/persist directory.  Also close the Home app on your iOS device. This will basically do a reset.  Then restart Homebridge and once up, open the Home app.  You will have to add Homebridge which will then allow you to add the Wemo devices.

Would be nice to have a feature with Homebridge to do a full restart.

**Comment by rwfisheriv** [comment]
Also having the same discovery issue.  I've tried the basic json configuration as above, and also explicitly calling out the specific WeMo device in the configuration...in both cases homebridge loads into the Home app but I never see the actual devices (WeMo Mini Switches).

**Comment by Mattserati** [comment]
Whilst I appreciate the advice above, it hasn't worked and my problem still persists.

**Comment by DMBlakeley** [comment]
Relooking at your log file I am not sure that you have Homebridge installed correctly.  The first lines indicate that files are not being found.  You also have more devices than just Wemo.  Would be good to see your whole config.sys file (please blank out any account username/passwords.  What platform do you have Homebridge running on?

**Comment by Mattserati** [comment]
DMBlakeley - I'm running Homebridge using Docker on a Synology DS415+

I'm not sure where I would find my config.sys file - any help greatly appreciated

**Comment by DMBlakeley** [comment]
FYI, Belkin just released their Wemo bridge today.  Price is $40 which is very reasonable considering all of the Wemo devices which you have already invested in.

Because I am curious I will do a little digging into Docker on a Synology NAS to see what I can learn.

**Comment by DMBlakeley** [comment]
Interesting that you can run Homebridge on your NAS.  Found this article on GitHub, https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology for your configuration, which seems to be quite complete with respect to installation and update of Homebridge.  The screen grab under "Method 2" shows the directory structure and where you can find the config.json and the 2 directories that I mentioned previously where the cache files are stored.

**Comment by Mattserati** [comment]
Thanks for your research DMBlakeley. Unfortunately at this stage Wemo Bridge is only available to US and Canadian customers, even though I received an email from them with a 40% discount code.

As for the running Homebridge on Synology NAS, I actually used the more popular Marcoraddatz version here: https://github.com/marcoraddatz/homebridge-docker which has worked previously, but at this stage seems to have issues - may try deleting it and installing the version you linked to, as the setup method is somewhat different and therefore may achieve different results.

**Comment by DMBlakeley** [comment]
Use of Marcoraddatz implementation explains the other platforms that I see loading in your log file.  I am running Homebride on an older Mac Mini.  

Before I suggest anything, I note on the marcoraddatz/homebridge-docker Github issues page that there is a recent entry for "Home App under iOS 11.2.1 does not find device" that you may want to look at.

**Comment by airmandan** [comment]
You are missing some common libraries needed to get this to work.  Many distros include them, but these errors are maddening on those that don’t.

sudo apt-get install avahi-daemon avahi-dnsconfd avahi-discover avahi-utils

sudo apt-get install libnss-mdns

Do this, and reinstall homebridge.  It will then work.

**Comment by Mattserati** [comment]
Thanks for the advice airmandan, but from what I can work out, Synology doesn't have apt-get as a command it recognises. I am assuming that you are suggesting SSH into the Synology from Terminal and type the above commands, but in both cases it errors as "command not found".

**Comment by jagooch** [comment]
I have the same issue, I'm running on CentOS 7 so we need the equivalent commands for yum package installation, not the apt-get packages.
