### ISSUE TITLE
Add WeMo Coffee Machine Support

### ISSUE THREAD

**Issue by nis1g** [donavanbecker/homebridge-platform-wemo#125]
Hello,

Kindly consider adding Wemo Mr. coffee support , the coffee info is here : http://www.belkin.com/us/support-article?articleNum=117715
![image](https://user-images.githubusercontent.com/35738480/35288853-ac449fd4-001a-11e8-8856-efe69d8a7932.png)
it involves one command "Brew" and status " Ready, Offline, Refill Water, Brewed at X:00 "
Thank you

**Comment by KaidenR** [comment]
I'm not sure there's a way to do this. It doesn't look like Homekit supports a "coffee maker" or similar service. Here's a list of the services HAP-Node does support:

AccessoryInformation
AirPurifier
AirQualitySensor
Battery
UUID
CameraRTPStreamManagement
CarbonDioxideSensor
CarbonMonoxideSensor
ContactSensor
Door
Doorbell
Fan
Fanv2
FilterMaintenance
GarageDoorOpener
HeaterCooler
HumidifierDehumidifier
HumiditySensor
LeakSensor
LightSensor
Lightbulb
LockManagement
LockMechanism
Microphone
MotionSensor
OccupancySensor
Outlet
SecuritySystem
ServiceLabel
Slat
SmokeSensor
Speaker
StatelessProgrammableSwitch
Switch
TemperatureSensor
Thermostat
Window
WindowCovering

**Comment by devbobo** [comment]
@KaidenR it could probably be implemented using a few different services like `Switch` and a `ContactSensor`

@nis1g  But it requires support to be added to [wemo-client](https://github.com/timonreinhard/wemo-client) first, you might want to try there are a starting point, as I don't have one of these devices for testing and I can't buy them here.
