### ISSUE TITLE
Change Color of Osram Lightstrips

### ISSUE THREAD

**Issue by airmandan** [donavanbecker/homebridge-platform-wemo#130]
So, it looks like the wemo-client package supports color control of Osram Lightstrips connected to the WeMo link.  I currently have successful on/off/brightness control of my light strips through this fantastic package, the only thing missing is color support of those devices.  Any chance we could get that support added in?

**Comment by fce** [comment]
+1

**Comment by devbobo** [comment]
@airmandan @fce I want to try to implement this...the only problem is that it appears that Osram have discontinued their products in Australia. Yesterday, I managed to track down a white Osram Lightify bulb and was able to implement the `ColorTemperature` characteristic. If I am unable to track any colour bulbs, I may need to take a stab at implementing the required characteristics and have you guys test it for me.

**Comment by airmandan** [comment]
@devbobo They're now marketed as Sylvania SMART+ at least on Amazon.  I did a pcap of the WeMo app changing the color for the Yonomi folks a bit ago and I'm pretty sure I've still got it kicking around.  If it would be helpful I'd be glad to send it over.

**Comment by airmandan** [comment]
POST /upnp/control/bridge1 HTTP/1.1
Content-Type: text/xml; charset="utf-8"
SOAPACTION: "urn:Belkin:service:bridge:1#SetDeviceStatus"
Content-Length: 663
HOST: 10.0.1.12:49153
User-Agent: CyberGarage-HTTP/1.0

<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<u:SetDeviceStatus xmlns:u="urn:Belkin:service:bridge:1">
<DeviceStatusList>&lt;DeviceStatusList&gt;
&lt;DeviceStatus&gt;
&lt;IsGroupAction&gt;NO&lt;/IsGroupAction&gt;
&lt;DeviceID available=&quot;YES&quot;&gt;84182600000B4AC3&lt;/DeviceID&gt;
&lt;CapabilityID&gt;10300,30301&lt;/CapabilityID&gt;
&lt;CapabilityValue&gt;46000:18000:0,0&lt;/CapabilityValue&gt;
&lt;/DeviceStatus&gt;
&lt;/DeviceStatusList&gt;
</DeviceStatusList>
</u:SetDeviceStatus>
</s:Body>
</s:Envelope>

I think I changed it to red with that.

**Comment by devbobo** [comment]
@airmandan thanks, I don't need to pcap data as `wemo-client` already supports these devices. It should be relatively straight forward to implement, but I like to do the testing myself as it cuts down the back and forth of troubleshooting any issues.

**Comment by airmandan** [comment]
Bump :)

**Comment by airmandan** [comment]
I see with 1.3.8 we gained the ability to adjust the color temperature of these strips, awesome!  Looks like the way the commit was made laid the groundwork for being able to change the RGB color as well.  Thanks for continuing to work on this project and I look forward to RGB functionality soon!

**Comment by devbobo** [comment]
@airmandan I ended up getting my hands on some `OSRAM Lightify CLA 60 RGBW` bulbs, but I couldn't get them to talk to the `WeMo Link`. Info I found at the time, indicated that they weren't supported.

**Comment by airmandan** [comment]
@devbobo unfortunately Belkin decided to lock down the WeMo app to make it impossible to pair the Link to any but their whitelisted devices, which includes a whopping five things, one of which is discontinued.

If you’re not able to source a supported Osram RGB product in AUS (the RGBW lightstrips or the Gardenspot Mini) I might be able to arrange to ship one to you, or I could take a stab at baking the feature into the project on my own.  Your temperature changing update gets it about 90% of the way there from reading the commit.
