### ISSUE TITLE
Multiple devices showing (ie.. Lightning Group, duplicate lights?)

### ISSUE THREAD

**Issue by SirNoble** [donavanbecker/homebridge-platform-wemo#135]
Hello All,
This plugin has been working very well for the past few months, due to recently changing my router, I had to change SSID/password for the Wemo Link and this is when the issues started to happen. 
I have multiple lightning groups which I can't seem to get rid of.  I have deleted the persist and accessory folder,  deleted and re-added the Homebridge bridge as well as reinstall the Platform-Wemo plugin.

Basically all the "Lightning groups" do not work, and there are duplicates of both Living Room and Hallway. 
All the devices with a cross I want removed. 

Please see screenshots, of Homebridge config, Wemo and Homekit application. 
![untitled](https://user-images.githubusercontent.com/31987189/38663005-f3689a7c-3e78-11e8-9b50-6d5a6fe3b10d.png)
![img_0502](https://user-images.githubusercontent.com/31987189/38662489-c9b087ae-3e77-11e8-8b34-6d1f3aa6ec09.PNG)
![img_0501](https://user-images.githubusercontent.com/31987189/38663679-d961f040-3e7a-11e8-9021-ef734deefc2c.PNG)

Please see screenshots:

**Comment by DMBlakeley** [comment]
You mention that you have a "Wemo Link".  Did you mean "Wemo Bridge"?  If you have the Wemo Bridge then you need to exclude these devices from Homebridge by using the "ignoredDevices" declaration in the configuration file (see documentation).  This would account for duplicate devices.

**Comment by SirNoble** [comment]
No @DMBlakely I’m talking about the Wemo Link which is the hub for Wemo lights, if I had the Wemo bridge I wouldn’t need to use this plugin ?

**Comment by isignedup** [comment]
Have you tried deleting Homebridge from the Home App and then reconnecting to Homebridge? Perhaps the Home App is caching things?

**Comment by SirNoble** [comment]
@isignedup Thank you for the suggestion, unfortunately I'v tried this multiple times without any luck.
