### ISSUE TITLE
All Lights Turning On

### ISSUE THREAD

**Issue by ayanm00** [donavanbecker/homebridge-platform-wemo#139]
I have 10 Wemo Light Switches and sometimes they all randomly turn on. When I go into Terminal on my Mac, it says Homebridge set the state of all of them to on. I disabled all of my automations (in both HomeKit and the Wemo app), but I'm still experiencing the issue. I've tried uninstalling homebridge-platform-wemo and reinstalling and deleting the persist and accessories folders, but that didn't help either. What can I do?

Thanks in advance!

**Comment by DMBlakeley** [comment]
This is certainly strange.  Are you sharing HomeKit with anybody?

**Comment by ayanm00** [comment]
Nope, it's just me.

**Comment by ayanm00** [comment]
Yeah, so all the devices are on 11.3.1, the HomePod is on 11.3, the Apple TV 4K and 4 are on 11.3, and the Mac that I have Homebridge running on is on High Sierra 10.13.4. I'm on the latest version of all my Homebridge plugins and Node.JS. I have an AirPort Time Capsule, and the wireless client list doesn't really have any devices out of the ordinary. I'm going to try and reformat my MacBook and see if that makes a difference. It's been a while since I clean installed anyways. If that doesn't help, maybe it's time to get an official Wemo Bridge, even though my Wemo app suspiciously detected my Homebridge as a Wemo Bridge.

**Comment by DMBlakeley** [comment]
You have a very similar setup to me. Seems a bit drastic to reformat your Mac but certainly no harm. I recently installed the Wemo bridge and it seems to work well.

**Comment by ayanm00** [comment]
Interesting... the lights did it again, but it appears that my Wemo amino Outlet is not affected by the issue.

**Comment by DMBlakeley** [comment]
Didn’t ask this before but are all of you Wemo devices up to the latest firmware?  The Wemo Mini Outlet is at a different firmware revision than the original outlet which it replaced.

**Comment by ayanm00** [comment]
Yeah, they're all on 11057. The Wemo app didn't give me a warning when I opened it.

**Comment by DMBlakeley** [comment]
My original Wemo Outlets and Light Switches are on 11057, however, my Wemo Mini Outlet is on 11059.  Not that this answers your original problem.  You don't happen to have Amazon Alexa or Google Assistant also connected to your Wemos?

**Comment by ayanm00** [comment]
Nope, all Apple here!

**Comment by DMBlakeley** [comment]
You have me quite stumped!  I have not experienced any issues with Homebridge or the Wemo app randomly turning on lights.

**Comment by ayanm00** [comment]
Let me know if you experience any issues with your official Wemo Bridge. I've read reports online that people have to power cycle it every once in a while because the Home app stops seeing it.

**Comment by DMBlakeley** [comment]
I have seen a Wemo plug disconnect a couple of times from the Wemo bridge but then will reconnect a few minutes later.  I have not seen an issue with the Home app not seeing the Wemo bridge.
