### ISSUE TITLE
Have Power Consumption for Wemo Insight Switch

### ISSUE THREAD

**Issue by CLARENNE-Q** [donavanbecker/homebridge-platform-wemo#151]
Hi,

Thanks for the beautiful module, it's really appreciated ! :-)

Do you plan to implement to show power consumption data for a Wemo Insight Switch?

The data is able to have with the wemo-client and will be a good features to add on setting information of homekit device.

Best regards,
Quentin

**Comment by KnicKnic** [comment]
It is in custom characteristic.
Current consumption is in https://github.com/rudders/homebridge-platform-wemo/blob/00913d119b36332ad4cdbb68aba6e782c915af40/index.js#L939-L950

Daily consumption is in https://github.com/rudders/homebridge-platform-wemo/blob/00913d119b36332ad4cdbb68aba6e782c915af40/index.js#L1157-L1171

Home app does not show this info, you can use one of many other homekit apps to see it.
https://itunes.apple.com/us/app/spaces-for-homekit/id1128103315?mt=8
https://itunes.apple.com/us/app/controller-for-homekit/id1198176727?mt=8
Are 2 examples of free ones that show this info.
