### ISSUE TITLE
ignoredDevices worked for most...

### ISSUE THREAD

**Issue by lucanaut** [donavanbecker/homebridge-platform-wemo#152]
Hello
I am using ignoredDevices to ignore a number of Wemo dimmers and Minis that are now directly connected to Homekit.  The number of devices total is approximately 25.  When I restart homebridge, 4 devices are still visible.  Not sure if I've hit some max?  I've tried breaking the command over two lines (two lines of ignoredDevices) but everything on the second line shows up in Homebridge.  

Any thoughts/ideas?

**Comment by ukypayne** [comment]
I know this is very old, but did it matter what order you put things in? Was it always the last 4 devices that would show up when they should be ignored?

**Comment by DMBlakeley** [comment]
I have 12 ignored devices slit over 3 lines for readability and have no issues. Don't seem to see a limit in the code limiting the max number.
