### ISSUE TITLE
Add support for Wemo Humidifier

### ISSUE THREAD

**Issue by chimai** [donavanbecker/homebridge-platform-wemo#153]
Could you please add support for [Wemo Holmes Humidifier](https://www.holmesproducts.com/wemo-humidifier.html)? The [wemo-client](https://github.com/timonreinhard/wemo-client) supports it and I would like to use my Humidifier inside HomeKit.

**Comment by alexargo** [comment]
Looks like the [Wemo Holmes Heater](https://www.holmesproducts.com/wemo-heater-mobile.html) is also supported by wemo-client. Would be cool to add this as well. I would try to add this myself, but I'm not super familiar with node dev environment... maybe I should figure it out.
