### ISSUE TITLE
reduce log information

### ISSUE THREAD

**Issue by vzlgdu** [donavanbecker/homebridge-platform-wemo#158]
Hi, is it possible reduce logging about energy consumption? In my configuration, every time that a wemo switch is activated, a record about energy consumption is written in the log every 5 seconds...

Thanks

**Comment by DMBlakeley** [comment]
I assume that you have a Wemo Insight switch.  Lines 1155 and 1156 in index.js creates the log entry whenever there is an increase in kWH of usage with a resolution in watts.  You could comment out these lines to stop the logging if this information is not useful to you.

**Comment by sherazan** [comment]
Please, where is locate index.js? My configuration is running on Raspbian… Thanks

**Comment by DMBlakeley** [comment]
I am using a Mac Mini and unfortunately I am not familiar with where the Homebridge files are located on Raspbian.

**Comment by sherazan** [comment]
Solved. The path is: /usr/local/lib/node_modules/homebridge-platform-wemo

The line involved is also the 923.

Restarted and solved.

Thanks a lot for your work!
