### ISSUE TITLE
Should be able to exclude Wemo Mini

### ISSUE THREAD

**Issue by Fuenti** [donavanbecker/homebridge-platform-wemo#159]
We should be able to exclude WeMo Minis from this homebridge. Homekit can now connect directly to WeMo Minis. Therefore, homebridge is not needed for them. Using the homebridge results in a second instance of every WeMo Mini. This is problematic.

**Comment by DMBlakeley** [comment]
I also have Wemo Minis that I have connected to the Wemo bridge.  Use the “ignoredDevices” option in the configuration file to exclude these Wemo Minis.  Enter the serial numbers in quotation marks for the Wemo Minis that you want to exclude.

**Comment by Fuenti** [comment]
I tried to exclude WeMo Minis using the recommendation above, but it doesn't seem to work. I found the serial numbers within HomeKit and I put them into Config.json as displayed below. I checked the numbers twice. What am I doing wrong?

 {
      "platform": "BelkinWeMo",
      "name": "WeMo Platform",
      "expected_accessories": "4",
      "ignoredDevices": ["221734K01058BD","221734K0107A8D","221734K01061C2","221734K0106102"]
    }

**Comment by DMBlakeley** [comment]
The “ignoredDevices” entry is of the correct format and the serial numbers also appear to be valid. I do not recognize the “expected_accessories” line and do not have in my config.json file. Also do not find a reference in the documentation.  Would suggest deleting this line.  Also assume that you either stopped and restarted homebridge or rebooted the device that you have homebridge running on.
