### ISSUE TITLE
Problem removing HD Cam

### ISSUE THREAD

**Issue by vzlgdu** [donavanbecker/homebridge-platform-wemo#161]
Hi, I'm using with success your plugin with 3 wemo switch. 
For tests I added an Belkin Netcam HD ad the related motion sensor was added to my homebridge istance. Now I removed the Netcam, but the sensor is always available in HB... I tried to remove the plugin and to reinstall again, but the Netcam is always available also if not active in my network. I would avoid to delete the "accessories" folder to solve this.
Do you have suggest?
Thanks

**Comment by DMBlakeley** [comment]
Easiest way is to delete the “cachedAccessories” file and restart Homebridge.  Alternately, you could you could make use of the ignoredDevices option listing the serial number of the camera. Once you stop and restart Homebridge the camera should be ignored.

**Comment by sherazan** [comment]
If I delete the “cachedAccessories” I will lose all my configuration... about to use ignoredDevices: I already use it but iit doesn't work...

**Comment by DMBlakeley** [comment]
Make sure that you have used serial numbers and not mac addresses in the ignored device statement, see example below:

          "platform": "BelkinWeMo",
          "name": "WeMo Platform",
          "ignoredDevices": ["23A59EV016xxxx"]

Also make sure that you reboot the device that you are running Homebridge on after you have made these changes.
