### ISSUE TITLE
Not working with Wemo firmware 11401

### ISSUE THREAD

**Issue by JimDog546** [donavanbecker/homebridge-platform-wemo#162]
I have been using this plugin successfully for over a year to interact with one [Wemo Switch Smart Plug](https://www.belkin.com/us/support-product?pid=01t80000002xFCbAAM&_ga=2.153674175.600045537.1564783425-2009546615.1564783425) and two [Wemo Smart Light Switches](http://www.belkin.com/us/support-product?pid=01t80000003JL9uAAG&_ga=2.99011737.600045537.1564783425-2009546615.1564783425).  I am not certain what firmware version they were running before, but after upgrading them to [firmware version 11401](https://community.wemo.com/s/question/0D52T00004iLxw2SAC/new-wemo-switch-and-sensor-firmware-version-11401) (WeMo_WW_2.00.11401.PVT-OWRT-SNS on the plug and WeMo_WW_2.00.11401.PVT-OWRT-LS on the switches) they are no longer working with this plugin.  They still appear in Home, I believe simply because they are cached accessories, but it doesn't update when the plug or switches turn on/off and turning them on/off in Home has no effect.  I don't believe the plugin can discover or communicate with them any longer.

When I start Homebridge the only message I get from this plugin is:
`[WeMo Platform] Initializing BelkinWeMo platform...`
and that's it.  Manually changing the state of the (probably cached) buttons in Home doesn't show anything in the Homebridge log.

Nothing has changed with my Homebridge installation.  The only change has been the firmware upgrade on the Wemos.

**Comment by DMBlakeley** [comment]
The Wemo Smart Plug and v2 of the Light Switch with this level of firmware provide native HomeKit support. You can add these devices as accessories directly. If these are your only devices you no longer need HomeBridge.

**Comment by JimDog546** [comment]
These are the first generation plug and switches. Neither have HomeKit support even in this newly released firmware. I'm familiar with it; I also have 3 Wemo Mini plugs that I am using natively with HomeKit (and have them excluded in my Homebridge config for this plugin), but that isn't an option for the older devices unfortunately.

**Comment by DMBlakeley** [comment]
I have my 1st generation devices connect to HomeKit with the Wemo Bridge rather than HomeBridge. Latest firmware update was a security update which may have blocked connection with HomeBridge.

**Comment by JimDog546** [comment]
After further analysis it seems like only the discovery process is affected by the new firmware. Adding all three devices as manualDevices in the configuration restored functionally.  Of course now I have to give them DHCP reservations as well but altogether it's an easy workaround.

**Comment by GarrettTrott** [comment]
> After further analysis it seems like only the discovery process is affected by the new firmware. Adding all three devices as manualDevices in the configuration restored functionally. Of course, now I have to give them DHCP reservations as well but altogether it's an easy workaround.

I'm having the same issue with firmware 11408 can please tell me how you manually added the devices in the config? I have 3 older switches I would love to get back working without buying the dedicated hub from wemo.

**Comment by JimDog546** [comment]
> can please tell me how you manually added the devices in the config?

@GarrettTrott: You'll need to know the IP addresses of the Wemo devices on your home network.  I do not know of a way to find this information in the Wemo app.  In my case I could view connected devices in my router and was able to identify them that way.  I was also able to assign them DHCP reservations which will keep their IP addresses the same.  Otherwise it's possible the IP addresses could change if the router loses power or reboots.

Once you have the IPs all you need to do is add the manualDevices parameter to your Homebridge config.json.  Below is what mine looks like.  You'll just need to replace the 192.168.86.x IP addresses with whatever is appropriate for you, but be sure to keep the :49153 part.  Note that I also disabled discovery since it no longer works for me.

`{
"platform": "BelkinWeMo",
"name": "WeMo Platform",
"manualDevices": ["http://192.168.86.21:49153/setup.xml","http://192.168.86.22:49153/setup.xml","http://192.168.86.23:49153/setup.xml"],
"discovery": false
}`

**Comment by GarrettTrott** [comment]
Thanks so much, JimDog546, worked perfectly!

**Comment by apollo316** [comment]
> > can please tell me how you manually added the devices in the config?
> 
> @GarrettTrott: You'll need to know the IP addresses of the Wemo devices on your home network. I do not know of a way to find this information in the Wemo app. In my case I could view connected devices in my router and was able to identify them that way. I was also able to assign them DHCP reservations which will keep their IP addresses the same. Otherwise it's possible the IP addresses could change if the router loses power or reboots.
> 
> Once you have the IPs all you need to do is add the manualDevices parameter to your Homebridge config.json. Below is what mine looks like. You'll just need to replace the 192.168.86.x IP addresses with whatever is appropriate for you, but be sure to keep the :49153 part. Note that I also disabled discovery since it no longer works for me.
> 
> `{`
> `"platform": "BelkinWeMo",`
> `"name": "WeMo Platform",`
> `"manualDevices": ["http://192.168.86.21:49153/setup.xml","http://192.168.86.22:49153/setup.xml","http://192.168.86.23:49153/setup.xml"],`
> `"discovery": false`
> `}`

Borked with this for HOURS! Your post saved **my sanity** and fixed my light switch gen1 and insight plug. THANK YOU!!! I also turned discovery off since all it needed to discover was these two devices.
