### ISSUE TITLE
Unable to set discovery = false

### ISSUE THREAD

**Issue by nathankellenicki** [donavanbecker/homebridge-platform-wemo#164]
A bug in the code means its currently impossible to turn discovery off

https://github.com/rudders/homebridge-platform-wemo/blob/00913d119b36332ad4cdbb68aba6e782c915af40/index.js#L110

Setting discovery to `false` will cause the initial condition in the `||` operator to fail, resulting it being set to `true` anyway. :)

In essence, `this.discovery = this.config.discovery || true;` is equal to `this.discovery = false || true;` which will always result in `this.discovery = true;`

Additionally, this line of code results in two Wemo client instances being created when initialised in Homekit. The first one has no options, and so discovery begins on all interfaces regardless of what options are passed in. This can be verified by setting `export DEBUG=true` and looking at the output of `node-ssdp`.

https://github.com/rudders/homebridge-platform-wemo/blob/00913d119b36332ad4cdbb68aba6e782c915af40/index.js#L29

**Comment by idcrook** [comment]
A way to have a falsifiable override for a Boolean var with a default value of true:

```JavaScript
this.discovery = this.config.discovery !== false; 
```
