### ISSUE TITLE
Fauxmo compatibility

### ISSUE THREAD

**Issue by andrewWandrewW** [donavanbecker/homebridge-platform-wemo#166]
I have a RPi3 with 8 channel relay set up for some home automation, I use a combination of fauxmo and a custom GPIO plugin and the devices display as 8 x WeMo switches to Alexa.

When adding this plugin to homebridge I can manually specify the device setup XML addresses and this allows them to be recognised as accessories with homebridge, I **can** control them on/off via homebridge-config-ui so they're definitely interacting correctly, however when trying to add the bridge to Home on an iPhone i get the message "Home couldn't connect to this accessory" (i've tried the usual, such as deleting the persist and accessories folder and changing MAC address in the config).

If i disable the WeMo plugin everythign works great again.

**Comment by lukelbro** [comment]
I have the same issue, I have also tried home assistant and have successfully added one device but I can’t figure out a way of adding the rest of them.
