### ISSUE TITLE
TypeError: Cannot read property 'setupDevice' of undefined at....

### ISSUE THREAD

**Issue by SirNoble** [donavanbecker/homebridge-platform-wemo#168]
Installed this plugin through HOOBS, been fine but now has been giving this error: 

`[Homebridge] [1/29/2020, 00:55:34] TypeError: Cannot read property 'setupDevice' of undefined at /home/hoobs/.hoobs/node_modules/homebridge-platform-wemo/index.js:132:30 at /home/hoobs/.hoobs/node_modules/wemo-client/client.js:174:7 at Parser.<anonymous> (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:304:18) at Parser.emit (events.js:210:5) at SAXParser.onclosetag (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:262:26) at emit (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:624:35) at emitNode (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:629:5) at closeTag (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:323:31) at Parser.parseString (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:5:59) at Object.exports.parseString (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:369:19) at parseResponse (/home/hoobs/.hoobs/node_modules/wemo-client/client.js:164:12) at module.exports.<anonymous> (/home/hoobs/.hoobs/node_modules/wemo-client/client.js:123:5) at Parser.<anonymous> (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:304:18) at Parser.emit (events.js:210:5) at SAXParser.onclosetag (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:262:26) at emit (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:624:35) at emitNode (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:629:5) at closeTag (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:889:7) at SAXParser.write (/home/hoobs/.hoobs/node_modules/sax/lib/sax.js:1436:13) at Parser.exports.Parser.Parser.parseString (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:323:31) at Parser.parseString (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:5:59) at Object.exports.parseString (/home/hoobs/.hoobs/node_modules/xml2js/lib/parser.js:369:19) at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/wemo-client/client.js:67:16) at IncomingMessage.emit (events.js:215:7) at endReadableNT (_stream_readable.js:1184:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)`

Config file below: 
> 
> {
>             "platform": "BelkinWeMo",
>             "name": "WeMo Platform",
>             "plugin_map": {
>                 "plugin_name": "homebridge-platform-wemo"
>             }

**Comment by donavanbecker** [comment]
looks like the same issue as #168, looks like a hoobs thing. I would recommend using regular [homebridge](https://github.com/homebridge/homebridge).
