### ISSUE TITLE
Error: The requested platform 'BelkinWeMo' was not registered by any plugin. at API.platform 

### ISSUE THREAD

**Issue by rmit-s3603463-stuart-wood** [donavanbecker/homebridge-platform-wemo#173]
Hi there, 
Getting this error after updating this plugin.

`
Error: The requested platform 'BelkinWeMo' was not registered by any plugin. at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19) at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47) at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14) at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12) at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63) at Module._compile (internal/modules/cjs/loader.js:959:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10) at Module.load (internal/modules/cjs/loader.js:815:32) at Function.Module._load (internal/modules/cjs/loader.js:727:14) at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) at internal/main/run_main_module.js:17:11
`

**Comment by donavanbecker** [comment]
what version of the plugin were you updating too?

**Comment by donavanbecker** [comment]
looks like the same issue as #168, looks like a hoobs thing. I would recommend using regular [homebridge](https://github.com/homebridge/homebridge).

**Comment by rmit-s3603463-stuart-wood** [comment]
I'm using the HOOBS UI, and I believe it updates from 1.3.8 to 1.5?

**Comment by twynne** [comment]
Updated to v1.5.1 today and have the same issue. I'm running native homebridge, nothing to do with hoobs here.

**Comment by donavanbecker** [comment]
I updated on a relatives plugin and had no issues.

**Comment by twynne** [comment]
No idea... Was working fine before. Only updated as saw there was an update in config UI.  Even with no devices configured it fails and prevents homebridge running. Remove it and all is fine again.

**Comment by donavanbecker** [comment]
if you install after you remove it, does it work?

**Comment by donavanbecker** [comment]
What is your node and npm version?

**Comment by donavanbecker** [comment]
update your node and npm to 12 or create and the plugin will work.

**Comment by twynne** [comment]
Updated node to latest, npm to latest.  Still didn't work initially as even with no reference to platform-wemo in my config it was still throwing errors.  I had to go and manually delete all reference to wemo from my server filesystem, reinstall, and then it appears to have worked.

Sorry to say updating anything on this server is starting to fill me with dread.  Inevitably it breaks something every. single. time.

**Comment by donavanbecker** [comment]
what's our homebridge version?

**Comment by twynne** [comment]
0.4.53

**Comment by donavanbecker** [comment]
do you have config-ui-x installed?

**Comment by twynne** [comment]
Yes, latest

**Comment by donavanbecker** [comment]
not sure then because I haven't had any issues at all.

**Comment by donavanbecker** [comment]
try v1.5.4
