### ISSUE TITLE
wemo coffee maker implementation?

### ISSUE THREAD

**Issue by tekuonline** [donavanbecker/homebridge-platform-wemo#23]
how easy is it to add a wemo coffee maker

**Comment by rudders** [comment]
This should be easy but I don't have one to test with. 

Could possibly take a stab at it if you want to be a tester for me.

Or feel free to fork and PR the result. The more contributors the better.

**Comment by tekuonline** [comment]
I can be the tester! Just bought one from wayfair.com for 50% off

**Comment by rudders** [comment]
What services would need to be supported - just on/off? OR did you have a grander vision?

**Comment by tekuonline** [comment]
I think this device is on all the time. All we need to implement is to brew the coffee, when asked to siri. Also it supports schedules which i dont know if homekit will be able to do, like "Siri schedule my coffee maker to brew at 6:00 am?"

**Comment by mmaxwell5** [comment]
I would love to have Coffee Maker integration as well.  I do not know if it is a standard switch function or if it is different function from their there products.  Attached is what it looks like in the WeMo App.  I am happy to do any testing.

![img_1647](https://cloud.githubusercontent.com/assets/16730904/12371430/0737bc9a-bbf9-11e5-8d68-dfd4ad89e615.jpg)

**Comment by rudders** [comment]
Thanks for offering to help. I'm away for a week so won't get to this till I get back but we'll sort it. Should be easy to add a simple variable to the code and have it behave as a switch - feel free to fork, fix and PR it if you're game.

**Comment by mmaxwell5** [comment]
Sounds great. No rush at all. 

I would be happy to try and fork it but I am a systems engineer and not so much a programmer. Wish I could. 

Much appreciate the help and please let me know if there is anything I can do. 

Michael Maxwell

**Comment by mmaxwell5** [comment]
Was just wondering if there has been any updates on this topic.

Thanks in advance.

**Comment by rudders** [comment]
Haven't progressed this as I've been busy with some error trapping in the main module and a dependency. Can you tell me what outcome you are looking for - Simple On/Off like a switch? I don;t know what services are available that we would align HomeKIt/Siri to other than this?

**Comment by tekuonline** [comment]
I guess its just on off.... here is the log from homebridge with wemo-platform 
_[WeMo Platform] Initializing platform accessory 'Bed Room Light'...
[WeMo Platform] Initializing platform accessory 'Kitchen Light'...
[WeMo Platform] Initializing platform accessory 'CoffeeMaker'...
Not implemented
[WeMo Platform] Bed Room Light binaryState: off
[WeMo Platform] Kitchen Light binaryState: off_

**Comment by rudders** [comment]
Feel free to try this simple change.

**Install:** `sudo npm install -g https://github.com/rudders/homebridge-platform-wemo#wemo-coffee-test`
**Rollback:** `sudo npm install -g homebridge-platform-wemo`

**Comment by tekuonline** [comment]
[WeMo Platform] Kitchen Light binaryState: on
[WeMo Platform] setOn: CoffeeMaker to off
[WeMo Platform] setOn: CoffeeMaker to on
[WeMo Platform] setOn: CoffeeMaker to off
[WeMo Platform] setOn: CoffeeMaker to on 

Nothing happens on the coffee maker although.

**Comment by rudders** [comment]
mmmm - odd. can you run `DEBUG=wemo-client homebridge` and post the entire log please.

**Comment by tekuonline** [comment]
[Wink] Initializing Wink platform...
[Wink] Fetching Wink devices.
[WeMo Platform] Initializing BelkinWeMo platform...
[WeMo Platform] Wemo Platform Plugin Loaded 
[WeMo Platform] Fetching the Wemo Accessories, expecting 3 and will wait 30 seconds to find them.
Loading 4 accessories...
[Vista 20P] Initializing Envisakit accessory...
[Garage Door] Initializing LiftMaster accessory...
[Living room TV] Initializing Http accessory...
[Living Room TV] Initializing Sony accessory...
  wemo-client Found device: {"root":{"$":{"xmlns":"urn:Belkin:device-1-0"},"specVersion":{"major":"1","minor":"0"},"device":{"deviceType":"urn:Belkin:device:lightswitch:1","friendlyName":"Kitchen Light","manufacturer":"Belkin International Inc.","manufacturerURL":"http://www.belkin.com","modelDescription":"Belkin Plugin Socket 1.0","modelName":"LightSwitch","modelNumber":"1.0","modelURL":"http://www.belkin.com/plugin/","serialNumber":"221547K1301091","UDN":"uuid:Lightswitch-1_0-221547K1301091","UPC":"123456789","macAddress":"94103E50F3D4","firmwareVersion":"WeMo_WW_2.00.10062.PVT-OWRT-LS","iconVersion":"0|49153","binaryState":"0","iconList":{"icon":{"mimetype":"jpg","width":"100","height":"100","depth":"100","url":"icon.jpg"}},"serviceList":{"service":[{"serviceType":"urn:Belkin:service:WiFiSetup:1","serviceId":"urn:Belkin:serviceId:WiFiSetup1","controlURL":"/upnp/control/WiFiSetup1","eventSubURL":"/upnp/event/WiFiSetup1","SCPDURL":"/setupservice.xml"},{"serviceType":"urn:Belkin:service:timesync:1","serviceId":"urn:Belkin:serviceId:timesync1","controlURL":"/upnp/control/timesync1","eventSubURL":"/upnp/event/timesync1","SCPDURL":"/timesyncservice.xml"},{"serviceType":"urn:Belkin:service:basicevent:1","serviceId":"urn:Belkin:serviceId:basicevent1","controlURL":"/upnp/control/basicevent1","eventSubURL":"/upnp/event/basicevent1","SCPDURL":"/eventservice.xml"},{"serviceType":"urn:Belkin:service:firmwareupdate:1","serviceId":"urn:Belkin:serviceId:firmwareupdate1","controlURL":"/upnp/control/firmwareupdate1","eventSubURL":"/upnp/event/firmwareupdate1","SCPDURL":"/firmwareupdate.xml"},{"serviceType":"urn:Belkin:service:rules:1","serviceId":"urn:Belkin:serviceId:rules1","controlURL":"/upnp/control/rules1","eventSubURL":"/upnp/event/rules1","SCPDURL":"/rulesservice.xml"},{"serviceType":"urn:Belkin:service:metainfo:1","serviceId":"urn:Belkin:serviceId:metainfo1","controlURL":"/upnp/control/metainfo1","eventSubURL":"/upnp/event/metainfo1","SCPDURL":"/metainfoservice.xml"},{"serviceType":"urn:Belkin:service:remoteaccess:1","serviceId":"urn:Belkin:serviceId:remoteaccess1","controlURL":"/upnp/control/remoteaccess1","eventSubURL":"/upnp/event/remoteaccess1","SCPDURL":"/remoteaccess.xml"},{"serviceType":"urn:Belkin:service:deviceinfo:1","serviceId":"urn:Belkin:serviceId:deviceinfo1","controlURL":"/upnp/control/deviceinfo1","eventSubURL":"/upnp/event/deviceinfo1","SCPDURL":"/deviceinfoservice.xml"},{"serviceType":"urn:Belkin:service:smartsetup:1","serviceId":"urn:Belkin:serviceId:smartsetup1","controlURL":"/upnp/control/smartsetup1","eventSubURL":"/upnp/event/smartsetup1","SCPDURL":"/smartsetup.xml"},{"serviceType":"urn:Belkin:service:manufacture:1","serviceId":"urn:Belkin:serviceId:manufacture1","controlURL":"/upnp/control/manufacture1","eventSubURL":"/upnp/event/manufacture1","SCPDURL":"/manufacture.xml"}]},"presentationURL":"/pluginpres.html","host":"10.0.1.2","port":"49153","callbackURL":"http://10.0.1.27:34229"}}} +0ms
[WeMo Platform] Found: Kitchen Light, type: lightswitch
[WeMo Platform] Kitchen Light is false
  wemo-client Initial subscription - Device: uuid:Lightswitch-1_0-221547K1301091, Service: urn:Belkin:service:basicevent:1 +25ms
[WeMo Platform] Discovered 1 accessories of 3 
  wemo-client Found device: {"root":{"$":{"xmlns":"urn:Belkin:device-1-0"},"specVersion":{"major":"1","minor":"0"},"device":{"deviceType":"urn:Belkin:device:lightswitch:1","friendlyName":"Bed Room Light","manufacturer":"Belkin International Inc.","manufacturerURL":"http://www.belkin.com","modelDescription":"Belkin Plugin Socket 1.0","modelName":"LightSwitch","modelNumber":"1.0","modelURL":"http://www.belkin.com/plugin/","serialNumber":"221414K1300E82","UDN":"uuid:Lightswitch-1_0-221414K1300E82","UPC":"123456789","macAddress":"B4750E90B7F0","firmwareVersion":"WeMo_WW_2.00.10062.PVT-OWRT-LS","iconVersion":"1|49153","binaryState":"0","iconList":{"icon":{"mimetype":"jpg","width":"100","height":"100","depth":"100","url":"icon.jpg"}},"serviceList":{"service":[{"serviceType":"urn:Belkin:service:WiFiSetup:1","serviceId":"urn:Belkin:serviceId:WiFiSetup1","controlURL":"/upnp/control/WiFiSetup1","eventSubURL":"/upnp/event/WiFiSetup1","SCPDURL":"/setupservice.xml"},{"serviceType":"urn:Belkin:service:timesync:1","serviceId":"urn:Belkin:serviceId:timesync1","controlURL":"/upnp/control/timesync1","eventSubURL":"/upnp/event/timesync1","SCPDURL":"/timesyncservice.xml"},{"serviceType":"urn:Belkin:service:basicevent:1","serviceId":"urn:Belkin:serviceId:basicevent1","controlURL":"/upnp/control/basicevent1","eventSubURL":"/upnp/event/basicevent1","SCPDURL":"/eventservice.xml"},{"serviceType":"urn:Belkin:service:firmwareupdate:1","serviceId":"urn:Belkin:serviceId:firmwareupdate1","controlURL":"/upnp/control/firmwareupdate1","eventSubURL":"/upnp/event/firmwareupdate1","SCPDURL":"/firmwareupdate.xml"},{"serviceType":"urn:Belkin:service:rules:1","serviceId":"urn:Belkin:serviceId:rules1","controlURL":"/upnp/control/rules1","eventSubURL":"/upnp/event/rules1","SCPDURL":"/rulesservice.xml"},{"serviceType":"urn:Belkin:service:metainfo:1","serviceId":"urn:Belkin:serviceId:metainfo1","controlURL":"/upnp/control/metainfo1","eventSubURL":"/upnp/event/metainfo1","SCPDURL":"/metainfoservice.xml"},{"serviceType":"urn:Belkin:service:remoteaccess:1","serviceId":"urn:Belkin:serviceId:remoteaccess1","controlURL":"/upnp/control/remoteaccess1","eventSubURL":"/upnp/event/remoteaccess1","SCPDURL":"/remoteaccess.xml"},{"serviceType":"urn:Belkin:service:deviceinfo:1","serviceId":"urn:Belkin:serviceId:deviceinfo1","controlURL":"/upnp/control/deviceinfo1","eventSubURL":"/upnp/event/deviceinfo1","SCPDURL":"/deviceinfoservice.xml"},{"serviceType":"urn:Belkin:service:smartsetup:1","serviceId":"urn:Belkin:serviceId:smartsetup1","controlURL":"/upnp/control/smartsetup1","eventSubURL":"/upnp/event/smartsetup1","SCPDURL":"/smartsetup.xml"},{"serviceType":"urn:Belkin:service:manufacture:1","serviceId":"urn:Belkin:serviceId:manufacture1","controlURL":"/upnp/control/manufacture1","eventSubURL":"/upnp/event/manufacture1","SCPDURL":"/manufacture.xml"}]},"presentationURL":"/pluginpres.html","host":"10.0.1.5","port":"49153","callbackURL":"http://10.0.1.27:34229"}}} +177ms
[WeMo Platform] Found: Bed Room Light, type: lightswitch
[WeMo Platform] Bed Room Light is false
  wemo-client Initial subscription - Device: uuid:Lightswitch-1_0-221414K1300E82, Service: urn:Belkin:service:basicevent:1 +7ms
[WeMo Platform] Discovered 2 accessories of 3 
  wemo-client Found device: {"root":{"$":{"xmlns":"urn:Belkin:device-1-0"},"specVersion":{"major":"1","minor":"0"},"device":{"deviceType":"urn:Belkin:device:CoffeeMaker:1","friendlyName":"CoffeeMaker","manufacturer":"Belkin International Inc.","manufacturerURL":"http://www.belkin.com","modelDescription":"Belkin Plugin Socket 1.0","modelName":"CoffeeMaker","modelNumber":"1.0","modelURL":"http://www.belkin.com/plugin/","serialNumber":"221424S0000951","UDN":"uuid:CoffeeMaker-1_0-221424S0000951","UPC":"123456789","macAddress":"94103E59B174","firmwareVersion":"WeMo_WW_2.00.10061.PVT-OWRT-Smart","iconVersion":"1|49154","binaryState":"0","DeviceID":"65539","DeviceFWVersion":"MC13805-140715","brandName":"MrCoffee","iconList":{"icon":{"mimetype":"jpg","width":"100","height":"100","depth":"100","url":"icon.jpg"}},"serviceList":{"service":[{"serviceType":"urn:Belkin:service:WiFiSetup:1","serviceId":"urn:Belkin:serviceId:WiFiSetup1","controlURL":"/upnp/control/WiFiSetup1","eventSubURL":"/upnp/event/WiFiSetup1","SCPDURL":"/setupservice.xml"},{"serviceType":"urn:Belkin:service:timesync:1","serviceId":"urn:Belkin:serviceId:timesync1","controlURL":"/upnp/control/timesync1","eventSubURL":"/upnp/event/timesync1","SCPDURL":"/timesyncservice.xml"},{"serviceType":"urn:Belkin:service:basicevent:1","serviceId":"urn:Belkin:serviceId:basicevent1","controlURL":"/upnp/control/basicevent1","eventSubURL":"/upnp/event/basicevent1","SCPDURL":"/eventservice.xml"},{"serviceType":"urn:Belkin:service:deviceevent:1","serviceId":"urn:Belkin:serviceId:deviceevent1","controlURL":"/upnp/control/deviceevent1","eventSubURL":"/upnp/event/deviceevent1","SCPDURL":"/deviceservice.xml"},{"serviceType":"urn:Belkin:service:firmwareupdate:1","serviceId":"urn:Belkin:serviceId:firmwareupdate1","controlURL":"/upnp/control/firmwareupdate1","eventSubURL":"/upnp/event/firmwareupdate1","SCPDURL":"/firmwareupdate.xml"},{"serviceType":"urn:Belkin:service:rules:1","serviceId":"urn:Belkin:serviceId:rules1","controlURL":"/upnp/control/rules1","eventSubURL":"/upnp/event/rules1","SCPDURL":"/rulesservice.xml"},{"serviceType":"urn:Belkin:service:metainfo:1","serviceId":"urn:Belkin:serviceId:metainfo1","controlURL":"/upnp/control/metainfo1","eventSubURL":"/upnp/event/metainfo1","SCPDURL":"/metainfoservice.xml"},{"serviceType":"urn:Belkin:service:remoteaccess:1","serviceId":"urn:Belkin:serviceId:remoteaccess1","controlURL":"/upnp/control/remoteaccess1","eventSubURL":"/upnp/event/remoteaccess1","SCPDURL":"/remoteaccess.xml"},{"serviceType":"urn:Belkin:service:deviceinfo:1","serviceId":"urn:Belkin:serviceId:deviceinfo1","controlURL":"/upnp/control/deviceinfo1","eventSubURL":"/upnp/event/deviceinfo1","SCPDURL":"/deviceinfoservice.xml"},{"serviceType":"urn:Belkin:service:smartsetup:1","serviceId":"urn:Belkin:serviceId:smartsetup1","controlURL":"/upnp/control/smartsetup1","eventSubURL":"/upnp/event/smartsetup1","SCPDURL":"/smartsetup.xml"},{"serviceType":"urn:Belkin:service:manufacture:1","serviceId":"urn:Belkin:serviceId:manufacture1","controlURL":"/upnp/control/manufacture1","eventSubURL":"/upnp/event/manufacture1","SCPDURL":"/manufacture.xml"}]},"presentationURL":"/pluginpres.html","host":"10.0.1.8","port":"49154","callbackURL":"http://10.0.1.27:34229"}}} +73ms
[WeMo Platform] Found: CoffeeMaker, type: CoffeeMaker
[WeMo Platform] CoffeeMaker is false
  wemo-client Initial subscription - Device: uuid:CoffeeMaker-1_0-221424S0000951, Service: urn:Belkin:service:basicevent:1 +4ms
[WeMo Platform] Discovered 3 accessories of 3 
[WeMo Platform] Woohoo!!! all 3 accessories found.
[WeMo Platform] Initializing platform accessory 'Kitchen Light'...
[WeMo Platform] Initializing platform accessory 'Bed Room Light'...
[WeMo Platform] Initializing platform accessory 'CoffeeMaker'...
  wemo-client Incoming Request for uuid:Lightswitch-1_0-221547K1301091: <e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<BinaryState>0</BinaryState>
</e:property>
</e:propertyset>

 +2s
[WeMo Platform] Kitchen Light binaryState: off
  wemo-client Incoming Request for uuid:Lightswitch-1_0-221414K1300E82: <e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<BinaryState>0</BinaryState>
</e:property>
</e:propertyset>

 +43ms
[WeMo Platform] Bed Room Light binaryState: off
  wemo-client Incoming Request for uuid:CoffeeMaker-1_0-221424S0000951: <e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<ParamString>1</ParamString>
</e:property>
</e:propertyset>

 +68ms
  wemo-client Unhandled Event: ParamString +3ms
[Wink] Device Ignored Not In HomeKit - Group hubs, ID 58658, Name Home
[Wink] Device Added - Group light_bulbs, ID 173786, Name Desk Lamp
[Wink] Initializing platform accessory 'Desk Lamp'...

**Comment by tekuonline** [comment]
Hope that helps

**Comment by rudders** [comment]
Could you include the logs from when you turn on and off the coffee maker please - can't understand why those commands are failing. thx

**Comment by tekuonline** [comment]
wemo-client SetBinaryState Response:  +8s { 's:Envelope': 
   { '$': 
      { 'xmlns:s': 'http://schemas.xmlsoap.org/soap/envelope/',
        's:encodingStyle': 'http://schemas.xmlsoap.org/soap/encoding/' },
     's:Body': { 's:Fault': [Object] } } }
[WeMo Platform] setOn: CoffeeMaker to off
  wemo-client SetBinaryState Response:  +1s { 's:Envelope': 
   { '$': 
      { 'xmlns:s': 'http://schemas.xmlsoap.org/soap/envelope/',
        's:encodingStyle': 'http://schemas.xmlsoap.org/soap/encoding/' },
     's:Body': { 's:Fault': [Object] } } }
[WeMo Platform] setOn: CoffeeMaker to on
  wemo-client SetBinaryState Response:  +1s { 's:Envelope': 
   { '$': 
      { 'xmlns:s': 'http://schemas.xmlsoap.org/soap/envelope/',
        's:encodingStyle': 'http://schemas.xmlsoap.org/soap/encoding/' },
     's:Body': { 's:Fault': [Object] } } }
[WeMo Platform] setOn: CoffeeMaker to off
  wemo-client SetBinaryState Response:  +2s { 's:Envelope': 
   { '$': 
      { 'xmlns:s': 'http://schemas.xmlsoap.org/soap/envelope/',
        's:encodingStyle': 'http://schemas.xmlsoap.org/soap/encoding/' },
     's:Body': { 's:Fault': [Object] } } }
[WeMo Platform] setOn: CoffeeMaker to on
  wemo-client Incoming Request for uuid:CoffeeMaker-1_0-221424S0000951: <e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0">
<e:property>
<attributeList>&lt;attribute&gt;&lt;name&gt;ModeTime&lt;/name&gt;&lt;value&gt;42&lt;/value&gt;&lt;prevalue&gt;41&lt;/prevalue&gt;&lt;ts&gt;1454986252&lt;/ts&gt;&lt;/attribute&gt;</attributeList>
</e:property>
</e:propertyset>

 +9s

**Comment by rudders** [comment]
Thanks - looks like we get some sort of fault so it will be hard to debug without a device to test on but I'll take a look sometime when I have some time spare. No promises.

**Comment by tekuonline** [comment]
This is what happens when i trace the packets using charles and use wemo app to brew coffee..
{
	"appEvents": {
		"appEvent": [{
			"appName": "WeMo1.14 rv:30211",
			"eventType": "2",
			"udid": "84989ba904568a23bdfc046c568f47568abe6476",
			"eventMessage": "App End session in Local mode.",
			"eventTS": "1454984095",
			"macAddress": "02:00:00:00:00:00"
		}, {
			"macAddress": "02:00:00:00:00:00",
			"appName": "WeMo1.14 rv:30211",
			"eventMessage": "App Start session in Local mode.",
			"eventType": "1",
			"udid": "84989ba904568a23bdfc046c568f47568abe6476",
			"eventTS": "1454986899"
		}]
	}
}

**Comment by mmaxwell5** [comment]
Was just wondering if anyone was able to make any progress on this?

Thanks in advance.

**Comment by tekuonline** [comment]
I do have some insight on this and I am looking to see if I can implement it on the wemo-client, in the mean time, I made my coffeemaker work with Siri using IFTTT plugin. I can say things like Siri, make me a coffee, and my WEMO coffee maker starts to brew. Thats all I have as of now.

**Comment by frankea** [comment]
I too think it would be great to add, however in the meantime what is the easiest way to suppress this message coming every 30 seconds filling up my logs:

`[2/11/2017, 2:54:47 PM] [WeMo Platform] Not Supported: CoffeeMaker [urn:Belkin:device:CoffeeMaker:1]`

**Comment by slcc2c** [comment]
This would be a great feature.

**Comment by devbobo** [comment]
Belkin has announced it will be releasing a WeMo HomeKit bridge in Fall, any devices that aren't currently support will hopefully be supported then.

**Comment by suculent** [comment]
I have an IoT coffee maker working. Except for on/off it has 8 various options where one must be selected to start making the coffee. Just need proper accessory prototype for that.

**Comment by fmp777** [comment]
Apparently WEMO can homekit now, but they excluded coffee machine :(
