### ISSUE TITLE
Add NetCam Camera Support

### ISSUE THREAD

**Issue by theAppleToThei** [donavanbecker/homebridge-platform-wemo#58]
HomeKit supports live video feeds, which would be nice for this project I think.

**Comment by tmur11** [comment]
@theAppleToThei you should add an enhancement label. Check out this thread KhaosT/HAP-NodeJS#253 for info on homekit video support.

**Comment by theAppleToThei** [comment]
@tmur11 Yes, I wanted to but I didn't see the option to add a label. Also, thanks for the thread. I will check it out.

**Comment by AppleTechy** [comment]
@khaost and @planetbeing got generic ip cameras working with Homebridge.
There is a pull request that just needs to finalized before it is merged.
If I didn't misunderstand what I was told.

**Comment by devbobo** [comment]
I don't believe that this is going to be possible, the research I have done indicates that accessing local video streams from the camera has been intentionally turned off by Belkin.

**Comment by distressedsk** [comment]
Hi guys, appreciate this is nearly a year old but would like to provide some feedback on successfully getting a NetCam HD "Live" in iOS 10...

- Installed FFMPEG
- Installed homebridge-camera-ffmpeg
- Setup Config (see below)
- Switch Netcam HD switch to "Setup" and wait for the green light...
- Add Camera in iOS
- Done...

Config:

"platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "Porch Test",
      "videoConfig": {
      	"source": "-re -i http://admin:admin@192.168.86.54/goform/video",
      	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 15
      }
    }
  ]

Unfortunately this renders the wemo-platform side of things unusable...

Hopefully this is useful somehow!

Cheers

**Comment by devbobo** [comment]
@distressedsk thanks, this is very useful, I'll take a closer look

**Comment by devbobo** [comment]
@distressedsk what version of the Netcam HD do you have ? I can't access that url on my Netcam HD.

Can you please paste the contents of this url in a response ?
http://192.168.86.54:49153/setup.xml

**Comment by distressedsk** [comment]
No problem, with the switch set down/normal mode I get:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<root xmlns="urn:Belkin:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:Belkin:device:NetCamSensor:1</deviceType>
<friendlyName>Porch</friendlyName>
<manufacturer>Belkin International Inc.</manufacturer>
<manufacturerURL>http://www.belkin.com</manufacturerURL>
<modelDescription>Belkin Plugin Socket 1.0</modelDescription>
<modelName>NetCamHDv1</modelName>
<modelNumber>1.0</modelNumber>
<modelURL>http://www.belkin.com/plugin/</modelURL>
<serialNumber>23A595V018F00C</serialNumber>
<UDN>uuid:NetCamSensor-1_0-23A595V018F00C</UDN>
<UPC>123456789</UPC>
<macAddress>EC1A5958F00C</macAddress>
<firmwareVersion>WeMo_NetCam_WW_2.00.10684.PVT</firmwareVersion>
<iconVersion>1|49153</iconVersion>
<binaryState>0</binaryState>
<iconList>
<icon>
<mimetype>jpg</mimetype>
<width>100</width>
<height>100</height>
<depth>100</depth>
<url>icon.jpg</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:Belkin:service:WiFiSetup:1</serviceType>
<serviceId>urn:Belkin:serviceId:WiFiSetup1</serviceId>
<controlURL>/upnp/control/WiFiSetup1</controlURL>
<eventSubURL>/upnp/event/WiFiSetup1</eventSubURL>
<SCPDURL>/setupservice.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:timesync:1</serviceType>
<serviceId>urn:Belkin:serviceId:timesync1</serviceId>
<controlURL>/upnp/control/timesync1</controlURL>
<eventSubURL>/upnp/event/timesync1</eventSubURL>
<SCPDURL>/timesyncservice.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:basicevent:1</serviceType>
<serviceId>urn:Belkin:serviceId:basicevent1</serviceId>
<controlURL>/upnp/control/basicevent1</controlURL>
<eventSubURL>/upnp/event/basicevent1</eventSubURL>
<SCPDURL>/eventservice.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:deviceevent:1</serviceType>
<serviceId>urn:Belkin:serviceId:deviceevent1</serviceId>
<controlURL>/upnp/control/deviceevent1</controlURL>
<eventSubURL>/upnp/event/deviceevent1</eventSubURL>
<SCPDURL>/deviceservice.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:crockpotevent:1</serviceType>
<serviceId>urn:Belkin:serviceId:crockpotevent1</serviceId>
<controlURL>/upnp/control/crockpot1</controlURL>
<eventSubURL>/upnp/event/crockpot1</eventSubURL>
<SCPDURL>/jardenservice.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:jardenevent:1</serviceType>
<serviceId>urn:Belkin:serviceId:jardenevent1</serviceId>
<controlURL>/upnp/control/jardenevent1</controlURL>
<eventSubURL>/upnp/event/jardenevent1</eventSubURL>
<SCPDURL>/jardenservice.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:firmwareupdate:1</serviceType>
<serviceId>urn:Belkin:serviceId:firmwareupdate1</serviceId>
<controlURL>/upnp/control/firmwareupdate1</controlURL>
<eventSubURL>/upnp/event/firmwareupdate1</eventSubURL>
<SCPDURL>/firmwareupdate.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:rules:1</serviceType>
<serviceId>urn:Belkin:serviceId:rules1</serviceId>
<controlURL>/upnp/control/rules1</controlURL>
<eventSubURL>/upnp/event/rules1</eventSubURL>
<SCPDURL>/rulesservice.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:metainfo:1</serviceType>
<serviceId>urn:Belkin:serviceId:metainfo1</serviceId>
<controlURL>/upnp/control/metainfo1</controlURL>
<eventSubURL>/upnp/event/metainfo1</eventSubURL>
<SCPDURL>/metainfoservice.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:remoteaccess:1</serviceType>
<serviceId>urn:Belkin:serviceId:remoteaccess1</serviceId>
<controlURL>/upnp/control/remoteaccess1</controlURL>
<eventSubURL>/upnp/event/remoteaccess1</eventSubURL>
<SCPDURL>/remoteaccess.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:deviceinfo:1</serviceType>
<serviceId>urn:Belkin:serviceId:deviceinfo1</serviceId>
<controlURL>/upnp/control/deviceinfo1</controlURL>
<eventSubURL>/upnp/event/deviceinfo1</eventSubURL>
<SCPDURL>/deviceinfoservice.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:smartsetup:1</serviceType>
<serviceId>urn:Belkin:serviceId:smartsetup1</serviceId>
<controlURL>/upnp/control/smartsetup1</controlURL>
<eventSubURL>/upnp/event/smartsetup1</eventSubURL>
<SCPDURL>/smartsetup.xml</SCPDURL>
</service>
<service>
<serviceType>urn:Belkin:service:manufacture:1</serviceType>
<serviceId>urn:Belkin:serviceId:manufacture1</serviceId>
<controlURL>/upnp/control/manufacture1</controlURL>
<eventSubURL>/upnp/event/manufacture1</eventSubURL>
<SCPDURL>/manufacture.xml</SCPDURL>
</service>
</serviceList>
<presentationURL>/pluginpres.html</presentationURL>
</device>
</root>

**Comment by distressedsk** [comment]
I couldn't gain access via the URL in any browser but to a gamble on it working in the plugin... which paid off until I realised the platform plugin would be disabled.

Reading this is what prompted me to take the punt: http://community.ispyconnect.com/ispybb2/viewtopic.php?t=507

3rd post down

**Comment by DMBlakeley** [comment]
I was able to get this up and running for 1 NetcamHDv1 camera.  A couple of clarification items for other novices as I am:

- FFMEG for Mac can be downloaded at: http://www.ffmpegmac.net.  The files from this download should be moved to  /usr/local/bin/.
- When adding the CONFIG file, change 192.168.86.54 to your local address for the camera.
- After adding the camera to the iOS home app, leave the switch on the camera in the setup position.  If you move to the camera position the feed reverts back through the Belkin servers.

Now my problem.  I have tried to add a second camera to the CONFIG file.  Each has a separate local address.  The second entry is recognized by the iOS Home app and allows me to add the camera, however, I do not get still or streaming live video from the second camera.  When homebridge starts up I have noted that 2 ports are assigned to the same camera:

[8/28/2017, 2:26:06 PM] Front Door is running on port 57696.
[8/28/2017, 2:26:06 PM] Front Door is running on port 57697.

I believe the second one should be "Living Room" rather than "Front Door".

Here is the portion of the config.json file for the 2 cameras:

      {
         "platform": "Camera-ffmpeg",
         "cameras": [
           {
              "name": "Front Door",
              "videoConfig": {
                "source": "-re -i http://admin:admin@10.0.1.15/goform/video",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 15
              }
            },
           {
              "name": "Living Room",
              "videoConfig": {
                "source": "-re -i http://admin:admin@10.0.1.18/goform/video",
                "maxStreams": 2,
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 15
              }
            }
          ]
       },

Any thoughts? The Front Door is a NetcamHDv1 and the Living Room is a NetcamHDv2.

**Comment by devbobo** [comment]
@DMBlakeley can you try just running with the `Living Room` camera ? My speculation is that `NetcamHDv2` do not work at all. I've been unable to get my `NetcamHDv2` camera working, and @distressedsk's camera is a `NetcamHDv1`...but maybe I was just doing it wrong.

**Comment by DMBlakeley** [comment]
Hi @devbobo, your suspicion was correct.  homebridge-camera-ffmpeg appears to be compatible with NetcamHDv1 but not v2.  With v1 I get both still and live video from the camera.  With the v2 camera, although it adds to HomeKit without issue, does not respond to a still request (as seen in the homebridge.log).  A "live" video request appears to not be sent.  

All a bit confusing as the XML files from the cameras appear to be identical only with difference in MAC address and S/N.  Both have the same firmware.  If I look at the AccessoryInfo.xxx.json files that are created when the devices are added (.homebridge/persist directory) there are some differences but unclear how this data is used in homebridge-camera-ffmpeg.

A couple other items:
- you need to fix the reserve the IP address for the camera in your router.  I have found that the IP address seems to change.  Not sure if this is the camera requesting a new IP or a router issue.  I am not able to save IP reservations in my router which is an issue.
- to track down problems I have found that deleting the .homebridge/accessories/cachedAccessories file helps.  Similarly, with the camera deletion of the .homebridge/persist/AccessoryInfo.xxx.json is required to reset the connection to HomeKit.
- I have observed once that after the NetcamHDv1 is in setup mode for a long time that video access seems to stop.  Have reset and will monitor.

Still trying to work my way through the homebridge-camera-ffmpeg archive to see if I can get a better understanding.

**Comment by LumpyPoopie** [comment]
I am following this thread with great interest! With updates over the past year or so, homebridge-platform-wemo has become one of my most stable and responsive HomeKit platforms. Netcam support would be icing on the cake.

I've got two NetcamHDv2 cameras, and would very much like to incorporate them into HomeKit.  using the above method, I was able to install and execute homebridge-camera-ffmpeg, and even add my two cameras as accessories into HomeKit.  However, when Homekit attempts to get a snapshot of a camera, Homebridge crashes, giving me this error:

`Snapshot -re -i http://admin:admin@10.0.1.32/goform/video -t 1 -s 480x270 -f image2 -
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

**Comment by DMBlakeley** [comment]
Just making sure that you also installed the FFMEG binary files?

I have both the v1 and v2 NetcamHD cameras.  The v1 camera has worked without issue, however, this is not the case with the v2 camera.  I have spent quite a bit of time trying to understand the difference between the 2 cameras and how the ffmpeg package handles them.  I have tinkered a bit with the JavaScript and have made some changes locally to the ffmpeg.js code on my computer.  The change have improved performance but have not cracked the v2 camera operation.  The best I get is a black screen for the v2 camera in the Home app.

I have also noticed that depending if you use an iPhone or an iPad to view the Home app that the snapshot image size is different.  On the iPad the snapshot request is for a 480x270 image, on the iPhone a 360x240 image.  The v1 camera seems to handle this difference without a problem.

I also really like to see this work for the v2 NetcamHD cameras so if there are any other suggestions in the community that would be greatly appreciated.

**Comment by LumpyPoopie** [comment]
Ah, yes, I failed to install the FFMPEG binary files.  Now that I've done so, homebridge doesn't crash on calling for a snapshot, but I get the same issue: no snapshot is relayed from homebridge to HomeKit on my v2 cameras. Sadly, I have no v1 cameras to use to verify my arrangement is working.  It is beyond me why there should be a discrepancy between the v1 and v2 cameras.

**Comment by 350d** [comment]
Hello guys! I guess I have a solution for ALL Blekin cameras here. Check my post here https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/138
So, it works on any camera with local stream and without. Delay is very small and with proper tweaks (session keep alive) it should be useful. Take a look.
