### ISSUE TITLE
Wemo Maker (as Window Shade)

### ISSUE THREAD

**Issue by tomwoodhams** [donavanbecker/homebridge-platform-wemo#73]
Hi, I have it controlling a Blind/Window Shade using the open and close status.

Is it possible to add the option so homebridge thinks its an automatic blind/ Window shade, not just a garage door opener?

**Comment by kenderson** [comment]
@tomwoodhams - I'm intrigued about your maker+shade implementation. Have you created any write ups? Thank you!

**Comment by tomwoodhams** [comment]
@kenderson Hi, Its a high Torque 12v motor >> H -Bridge >> Arduino Uno >> Wemo Maker
The wemo maker is set to momentary, when homeBridge triggers the Wemo Maker, the arduino detects a voltage in the connected pin, it tells the H Bridge either spin the motor one way or the other (depending on what happened before). 

The motor is connected to the shaft of the venetian blind - it only tilts the slats of the blind - it doesn't raise or lower it.

Will get some photo's when completely finished, just hoping @rudders will add the Window Shade option :)

**Comment by devbobo** [comment]
@tomwoodhams do you have anything connected into the sensor input to confirm open or closed state ?

**Comment by tomwoodhams** [comment]
Hi, no I do not at the moment, thinking about adding a reed switch or similar.
