### ISSUE TITLE
Wemo Maker Name Change

### ISSUE THREAD

**Issue by LumpyPoopie** [donavanbecker/homebridge-platform-wemo#76]
I've recently re-purposed a WeMo Maker from controlling an Alarm Clock to a Garage Door.  It works wonderfully as a garage door opener with Homebridge and the most recent release of homebridge-platform-wemo.  However, the old name of "Alarm Clock" seems to have stuck in homebridge.  I've updated the name in the WeMo app, and I changed the name in iOS Homekit, however, the name keeps getting reset in Homekit to "Alarm Clock."  Now I have to tell Siri to "Open the Alarm Clock" to get the door to open, much to my wife's amusement.

How can I get the name change in WeMo to propagate through homebridge into homekit?

**Comment by tmur11** [comment]
@LumpyPoopie Have you tried deleting the homebridge persist folder? Restart homebridge and it will build a new one, although keep in mind you will have to repair homebridge with homekit. I'd recommend you delete your existing homebridge bridge from homekit before deleting the persist folder.

**Comment by devbobo** [comment]
@LumpyPoopie unfortunately, this is a bit of achilles heal of HomeKit/Homebridge, devices can't be renamed by the service after adding  them to HomeKit, they can only be renamed from within a HomeKit app.

I'd suggest download Hesperus from the app store, it has some additional built-in features which I have enabled for this platform, including removing devices. With the new way accessories get persisted, I don't recommend using @tmur11's method.

**Comment by LumpyPoopie** [comment]
@devbobo thanks for suggesting Hesperus.  I've used both Hesperus and the powerful "Home" app by Matthias Hochgatterer to update the device name.  It sticks for a few days, but then resets back to the "Alarm Clock" name that is apparently stored in the homebridge persist folder.

@tmur11 I have not tried deleting the homebridge persist folder.  I've been hesitant to delete the existing homebridge bridge from homekit & starting over.  I've got many different services plugged into homebride, and it'd be a hassle to set them all back up in homekit. 

@devbobo @tmur11 is there a way to edit/refresh the wemo names in the homebridge persist folder without deleting homebridge from homekit? I'd rather just call my garage door an alarm clock than set everything up again.

**Comment by knosalaa** [comment]
Lumpypoopie,
Thanks for your comments, I have been using wemo maker for some time now. I always wanted to use native Apple Homekit and even purchased wemo bridge but as you know it do not support wemo maker. Can you please post source or your directions how to bring wemo maker (I’m using it for garage door) so HomeKit will recognize it and I can use it with Siri?
Thanks a bunch
